### ISSUE TITLE
Inheritance 

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/isabelchacon#1]
https://github.com/CodingDojo-MEAN-06-18/isabelchacon/blob/74cd4f1fac2a1dc02744e96f6bc4fd0c8b628cc1/angular/powerlevels/src/app/power/power.component.ts#L8-L13

I assume you've just started this assignment. Just want to point out that when creating your `level` components, it provides a great opportunity for inheritance.

**Comment by anachacon** [comment]
Thank you Jason!


Yeah I was just thinking about creating just one 'human' component and extend it to several sayan classes and just change the multiplier, as opposed to creating one individual component per sayan element for example. Is this what you mean?


Isabel Chacon, M.Ed.
Front End Web Developer
Cogwheel Clinic for Neurodevelopment
http://www.CogwheelClinic.com<http://www.cogwheelclinic.com/>


________________________________

**Comment by dojo-json** [comment]
Yes, that is exactly what I mean. If you do it this way you can reuse a single html template across all levels (human, saiyan, etc).

**Comment by anachacon** [comment]
Excellent! Will do.
