### ISSUE TITLE
Observable

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/isabelchacon#2]
https://github.com/CodingDojo-MEAN-06-18/isabelchacon/blob/742ac73167e7122d80b672fd885af6d0710f6ea4/angular/ninjagold/src/app/data.service.ts#L6-L9

Instead of using an Object to keep track of gold, try using a more appropriate data type, like an Observable. You should be streaming information to your components. Not relying on an object reference to update gold count.

**Comment by anachacon** [comment]
Thank you for the clarification Jason! I was confused regarding whether we could use observables or not, since the assignment comes before the Observables section in the platform. I'll make the adjustments!
